db = [
  {"phrase":"clarifai","tag":"Clarifai"},
  {"phrase":"wacom","tag":"Wacom"},
  {"phrase":"machine learning","tag":"machine learning"},
  {"phrase":"imgur","tag":"Imgur"},
  {"phrase":"html5","tag":"HTML5"},
  {"phrase":"html 5 ","tag":"HTML5"},
  {"phrase":"html","tag":"HTML5"},
  {"phrase":"javascript","tag":"JavaScript"},
  {"phrase":"js","tag":"JavaScript"},
  {"phrase":"pocket","tag":"Pocket"},
  {"phrase":"php","tag":"PHP"},
  {"phrase":"json","tag":"JSON"},
  {"phrase":"oauth","tag":"Oauth"},
  {"phrase":"xpath","tag":"xpath"},
  {"phrase":"stackoverflow","tag":"StackOverflow"},
  {"phrase":"stack overflow","tag":"StackOverflow"},
  {"phrase":"SO","tag":"StackOverflow"},
  {"phrase":"github","tag":"GitHub"},
  {"phrase":"GH","tag":"GitHub"},
  {"phrase":"hackernews","tag":"HackerNews"},
  {"phrase":"hacker news","tag":"HackerNews"},
  {"phrase":"HN","tag":"HackerNews"},
  {"phrase":"jquery","tag":"jQuery"},
  {"phrase":"grunt","tag":"grunt"},
  {"phrase":"grunt.js","tag":"grunt"},
  {"phrase":"gulp","tag":"gulp"},
  {"phrase":"gulp.js","tag":"gulp"}
]
